spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:6060/pepperfrydb
    username: root
    password: root
  jpa:
    show-sql: false
    generate-ddl: false
product:
  defaultCategory: fashion
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka